/** Current sys/ref source map. Keep node IDs in code reviews and asset reports. */
export const figmaScreenMap = {
  welcome: { nodeId: '20:873', exportName: 'WelcomeScreen' },
  register: { nodeId: '27:946', exportName: 'RegisterScreen' },
  login: { nodeId: '27:999', exportName: 'LoginScreen' },
  importMusic: { nodeId: '29:1426', exportName: 'ImportMusicScreen' },
  spotifyLogin: { nodeId: '34:1543', exportName: 'ConnectSpotifyScreen', state: 'login' },
  spotifyImporting: { nodeId: '34:1590', exportName: 'ConnectSpotifyScreen', state: 'importing' },
  spotifyError: { nodeId: '34:1639', exportName: 'ConnectSpotifyScreen', state: 'error' },
  listeningNotGranted: { nodeId: '35:1725', exportName: 'ListeningPermissionScreen', granted: false },
  listeningGranted: { nodeId: '35:1783', exportName: 'ListeningPermissionScreen', granted: true },
  portraitFull: { nodeId: '38:1839', exportName: 'PortraitScreen' },
  portraitViewport: { nodeId: '38:2003', exportName: 'PortraitScreen' },
  libraryAnalytics: { nodeId: '49:2612', exportName: 'LibraryAnalyticsScreen' },
  libraryGenreOpen: { nodeId: '49:3248', exportName: 'LibraryGenreOpenScreen' },
  libraryEraOpen: { nodeId: '49:3320', exportName: 'LibraryEraOpenScreen' },
  librarySortOpen: { nodeId: '49:3392', exportName: 'LibrarySortOpenScreen' },
  libraryDiscover: { nodeId: '64:4887', exportName: 'LibraryTracksScreen', mode: 'discover' },
  erasPremium: { nodeId: '66:5120', exportName: 'ErasPremiumScreen' },
  erasFree: { nodeId: '66:5331', exportName: 'ErasFreeScreen' },
  erasEmpty: { nodeId: '66:5466', exportName: 'ErasEmptyScreen' },
  erasRename: { nodeId: '66:5561', exportName: 'ErasRenameScreen' },
  constellation: { nodeId: '91:7094', exportName: 'Constellation' },
  logoPrimary: { nodeId: '83:6518', asset: 'assets/musicdude-logo-primary.svg' },
  logoDark: { nodeId: '90:6822', asset: 'assets/musicdude-logo-dark.svg' },
} as const;
